# Generated by Django 4.2.7 on 2023-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlist',
            name='request_body',
            field=models.TextField(default='{}', null=True),
        ),
    ]
